# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: backend-book-club_development

# test:
#   <<: *default
#   database: backend-book-club_test

# production:
#   <<: *default
#   database: backend-book-club_production
#   username: backend-book-club
#   password: <%= ENV['BACKEND-BOOK-CLUB_DATABASE_PASSWORD'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: backend-book-club_development

test:
  <<: *default
  database: backend-book-club_test

production:
  <<: *default
  database: backend-book-club_production
  username: backend-book-club
  password: <%= ENV['BACKEND-BOOK-CLUB_DATABASE_PASSWORD'] %>